uniprot_selected_term_types = c('UniProtKB-AC',
                                'UniProtKB-ID',
                                'GeneID (EntrezGene)',
                                'RefSeq',
                                'GI',
                                'PDB',
                                'GO',
                                'UniRef100',
                                'UniRef90',
                                'UniRef50',
                                'UniParc',
                                'PIR',
                                'NCBI-taxon',
                                'MIM',
                                'UniGene',
                                'PubMed',
                                'EMBL',
                                'EMBL-CDS',
                                'Ensembl',
                                'Ensembl_TRS',
                                'Ensembl_PRO',
                                'Additional PubMed')
